const router = require('express').Router()
const Controller = require('../controllers/admin')
const middleware = require('../middleware/checkLoginAdmin')

router.get('/', middleware, Controller.showProfile)
router.get('/login', Controller.login)
router.post('/login', Controller.checkAccount)
router.get('/logout', Controller.logout)
router.get('/addTrain', middleware, Controller.addFormTrain)
router.post('/addTrain', middleware, Controller.addTrain)
router.get('/addDestination', middleware, Controller.addFormDestination)
router.post('/addDestination', middleware, Controller.addDestination)
router.get('/listTrain', middleware, Controller.showTrains)
router.get('/listDestination', middleware, Controller.showDestinations)
router.get('/update/:id/train', middleware, Controller.formUpdateTrain)
router.post('/update/:id/train', middleware, Controller.updateTrain)
router.get('/update/:id/destination', middleware, Controller.formUpdateDestination)
router.post('/update/:id/destination', middleware, Controller.updateDestination)
router.get('/delete/:id/train', middleware, Controller.deleteTrain)
router.get('/delete/:id/destination', middleware, Controller.deleteDestination)

module.exports = router